### ISSUE TITLE
Feature idea : Only accept parts of suggestion using prefix argument

### ISSUE THREAD

**Issue by hemanta212** [zerolfx/copilot.el#10]
Copilot tends to provide one/multiple lines of completion at a single time.

Sometimes, it is useful to only accept the first few words of suggestion. This is particularly true when writing documentation/prose where I often want to use the copilot completion for difficult error-prone spellings and words.

So, I was wondering if it would be possible to give a prefix argument while hitting the tab key (or other key bound to `copilot-accept-completion` to only accept the first x words.

**Comment by zerolfx** [comment]
I agree with you. Sometimes, I need to hit the tab and delete the unwanted part to accept only the first few words. Overall, it saves time for me, but we can make it better as you suggested.

I will implement it as a unique feature (not provided by Copilot plugins from other editors).

**Comment by hemanta212** [comment]
Just tried it and it works great. As an evil user I realized i had to figure out some way to give universal argument but now that i tested it works like a charm.

Thank you so much @zerolfx  for this great addition and for the work on this awesome plugin. 🎉
