### ISSUE TITLE
$KBD not defined

### ISSUE THREAD

**Issue by chriselrod** [zerolfx/copilot.el#102]
Hi, I'm using
```elisp
(use-package copilot
  :delight
  :straight (:host github :repo "zerolfx/copilot.el" :files ("dist" "*.el"))
  :hook prog-mode
  :bind (:map copilot-completion-map
              ("C-M-<return>" . copilot-accept-completion)
              ("C-M-RET" . copilot-accept-completion)
              ("M-<return>" . copilot-accept-completion-by-line)
              ("M-RET" . copilot-accept-completion-by-line)))

```

I will often see completion suggestions from copilot, but get `M-RET` not defined errors when actually trying to accept copilot's suggestion.
Any idea what the problem may be, or advice on how to debug this?

For some reason, it seems like `copilot-completion-map` is not active, even while I see copilot's suggestion.

Sometimes, it does work. I've not yet noticed a pattern, but perhaps I should take notes.
Has anyone else noticed this? Or is there something obviously wrong with my config?

**Comment by zerolfx** [comment]
See #86. You can try to set a higher priority number here:

https://github.com/zerolfx/copilot.el/blob/bc91709ff2402b4e4c370b262af67ea199c297f3/copilot.el#LL428C9-L428C39

**Comment by chriselrod** [comment]
Thanks. I have the problem when `julia-ts-mode` is active and I have unmatched parenthesis.

I don't use smartparens, but do use `show-paren-mode`.

I've noticed this occasionally with `c++-ts-mode`, but it happens rarely. It isn't triggered merely by unmatched parenthesis.
But that is enough to trigger it with `julia-ts-mode`.

**Comment by chriselrod** [comment]
I do still have this issue. I'll try increasing the priority.

**Comment by chriselrod** [comment]
I still have it in `julia-ts-mode` and `c++-ts-mode`.

**Comment by zerolfx** [comment]
If increasing the value of the `'priority` property does not solve your issue, you can set up global keybindings. 

Example: https://github.com/zerolfx/copilot.el/tree/7379dce63a26a6546d6f56679c00b97cfbd86d5c#example-of-using-tab-with-company-mode

**Comment by chriselrod** [comment]
> If increasing the value of the `'priority` property does not solve your issue, you can set up global keybindings.
> 
> Example: https://github.com/zerolfx/copilot.el/tree/7379dce63a26a6546d6f56679c00b97cfbd86d5c#example-of-using-tab-with-company-mode

This is what I'm doing for now.
```elisp
(use-package copilot
  :delight
  :straight (:host github :repo "zerolfx/copilot.el" :files ("dist" "*.el"))
  :hook prog-mode
  :bind (;;:map copilot-completion-map
         ("C-M-<return>" . copilot-accept-completion)
         ("C-M-RET" . copilot-accept-completion)
         ("M-<return>" . copilot-accept-completion-by-line)
         ("M-RET" . copilot-accept-completion-by-line))
  :custom (copilot-idle-delay 0.25))
```
This has been working for me.
