### ISSUE TITLE
[Feature Request] Better / more flexible accept completion by word

### ISSUE THREAD

**Issue by richsmith** [zerolfx/copilot.el#105]
Great work with this package!

It would be great if `copilot-accept-completion-by-word` was a bit more flexible. It looks like at the moment it just considers word boundaries as whitespace. However, this doesn't work for a lot of languages.

E.g. Python:
`foo(bar).filter(x=y).accept_when(deleted=True)`
would all be considered one word.

I think it would be preferable if `copilot-accept-completion-by-word` would treat punctuation as a word boundary, or if whatever mechanism Emacs uses to decide word boundaries was used, or the regex that decides it was customisable.

**Comment by zerolfx** [comment]
```elisp
(defun copilot-accept-completion-by-word-new (n-word)
  "Accept first N-WORD words of completion."
  (interactive "p")
  (setq n-word (or n-word 1))
  (copilot-accept-completion (lambda (completion)
                               (with-temp-buffer
                                 (insert completion)
                                 (goto-char (point-min))
                                 (forward-word n-word)
                                 (buffer-substring-no-properties (point-min) (point))))))

(advice-add 'copilot-accept-completion-by-word :override #'copilot-accept-completion-by-word-new)
```

Could you try this in your config and see if it helps?

**Comment by richsmith** [comment]
Thanks for looking into this! Seems to work well, thanks.

**Comment by zerolfx** [comment]
Thank you for verifying the patch. I applied these changes to the main branch.
