### ISSUE TITLE
Authentication failure: Timed out Authenticated as GitHub user nil for WSL emacs

### ISSUE THREAD

**Issue by milanglacier** [zerolfx/copilot.el#107]
`emacs version`

```
GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.36, cairo version 1.16.0)
```

`copilot version` fb4d4e1

`node version`: 18.4.2

**Step to reproduce**:

1. `M-x copilot-login`, remember the one-time code, press ENTER
2. open the github authorization link via windows web browser (chrome)
3. input the code, press enter, then click on the button to confirm authorization.
4. Back to emacs, press enter again
5. Copilot.el prompts `verifying`
6. get the error: `Authentication failure: Timed out Authenticated as GitHub user nil`

**Comment by zerolfx** [comment]
Please paste your `*copilot events*` buffer.

I can't reproduce this error. It seems to be your network problem.
