### ISSUE TITLE
Weird rendering / positioning issues with company-box and copilot.

### ISSUE THREAD

**Issue by wusticality** [zerolfx/copilot.el#109]
I've been using `company-box` in conjunction with this package. In some cases, it works as expected:

![image](https://user-images.githubusercontent.com/1028792/227656193-89cffb18-f290-4eac-88bf-c19afa43a202.png)

Here, both `lsp-mode` candidates and copilot candidates are shown. However, other times, things to not work as expected, namely, the position of the `company-box` child frame is moved by the copilot candidate overlay, and the color of the child overlay for `company-box` is affected by the background color of the copilot overlay:

![image](https://user-images.githubusercontent.com/1028792/227656829-db8599d9-b2f5-4260-975a-dd903ed51c67.png)

This happens about 50% of the time for me. Thanks!

**Comment by zerolfx** [comment]
https://github.com/zerolfx/copilot.el/blob/d4519e178217309833b98eb0f2bfbddc4edb4c2e/copilot.el#L539

Please try to remove this line and see what happens.

**Comment by wusticality** [comment]
Hey, thanks for the prompt response. Commented out that line but it's still happening once the candidate is rendered in the copilot overlay:

![image](https://user-images.githubusercontent.com/1028792/227762477-cc617576-c8bc-4c9c-a4f5-3dcc87e9d561.png)

**Comment by zerolfx** [comment]
Sorry for missing some essential details.

I can't reproduce this problem, so I can't help you much.

Removing this line should fix the color problem but not the position problem. After confirming the color problem is fixed, you can work on fixing the position problem, which is overlay-related. My solution for the position problem is using that `copilot--posn-advice`, but in your case, it seems to be inadequate and fails 50% of the time.

**Comment by wusticality** [comment]
Heya, thanks again for your time. Interesting that you're not seeing this on your end. Have you tried using `copilot` in conjunction with something like `lsp-mode` that has some latency? This behavior happens both on my Linux box and on my MacBook Pro. 

Near as I can tell, it seems to happen if `copilot` has candidates to display _before_ `company-box`. If so, the `company-box` child frame gets pushed to the right of it. Perhaps a way to reproduce this on your end would be to show a `company-box` after a delay or to try using `lsp-mode` which has more latency? I'm happy to help in any way that I can.

Commenting out that advice doesn't seem to help either way.

**Comment by zerolfx** [comment]
I can reproduce this problem after upgrading all my plugins. I will investigate it soon.

**Comment by wusticality** [comment]
Thanks so much for this, at least on my MacBook pro, this issue appears to be fixed. :)

I won't be able to test on my Linux box until I'm back home in a week or so, should i keep this open until then?

**Comment by zerolfx** [comment]
![image](https://user-images.githubusercontent.com/20219056/228160767-e1112643-7d4c-43c1-af75-71e8add653a3.png)

@wusticality Are there any specific prerequisites required to trigger the color issue, such as only happening at the end of lines? I'm unable to reproduce the issue on my end.
