### ISSUE TITLE
Check predicates while actually displaying completion

### ISSUE THREAD

**Issue by blahgeek** [zerolfx/copilot.el#110]
Currently, both `copilot-disable-predicates` and `copilot-enable-predicates` are only checked before starting completion. When the completion results is returned asynchronously, they are always displayed even if the predicates are no longer true. This makes it hard for use cases like disabling copilot when company-mode is active, since company mode is also triggered asynchronously.

**Comment by zerolfx** [comment]
Added `copilot-disable-display-predicates` and `copilot-enable-display-predicates`, which will be checked before showing completions.

**Comment by blahgeek** [comment]
That was fast! Thank you so much for your work!
