### ISSUE TITLE
How do I change the text color of the completion suggestion?

### ISSUE THREAD

**Issue by lubert** [zerolfx/copilot.el#112]
Not sure if this is something configurable through copilot.el, wondering if there's variable I can set to change the text color of the completion suggestion, which looks a little light with my color scheme. Appreciate any leads, thanks!

<img width="459" alt="Screen Shot 2023-03-28 at 11 03 09 AM" src="https://user-images.githubusercontent.com/4617974/228390880-b4d685f8-d801-4628-a33a-0f74073bd4d8.png">

**Comment by zerolfx** [comment]
Is `copilot-overlay-face` what you want?

**Comment by lubert** [comment]
Yes, that's exactly it! Thank you!
