### ISSUE TITLE
args-out-of-range error when using copilot with narrowing enabled

### ISSUE THREAD

**Issue by LemonBreezes** [zerolfx/copilot.el#115]
Error running timer ‘copilot--post-command-debounce’: (args-out-of-range 4646 18925 34646)

This occurs while using Copilot with a narrowed buffer while at the end of the narrowed buffer.

**Comment by zerolfx** [comment]
Could you provide the call stack? (use `toggle-debug-on-error`)

**Comment by zerolfx** [comment]
I've just fixed a bug related to narrowing. Please upgrade and give it another try.

**Comment by LemonBreezes** [comment]
> I've just fixed a bug related to narrowing. Please upgrade and give it another try.

Thanks. The new behavior is better but not perfect. Now it only shows one character from the completion if I am at the very end of the narrowed buffer
![image](https://user-images.githubusercontent.com/29102529/228907967-a486c590-b6f0-4e28-b467-6ab0983bf15a.png)

**Comment by zerolfx** [comment]
![image](https://user-images.githubusercontent.com/20219056/229066433-77be1182-cfb9-4bb9-a46e-f71686639a10.png)
![image](https://user-images.githubusercontent.com/20219056/229067077-32a1c0c7-253b-440c-9d4f-e3f27b586826.png)

Unfortunately, I can't reproduce the new problem.  Does the issue occur 100% of the time at the end of a narrowed buffer? Can you provide detailed steps to reproduce it?
