### ISSUE TITLE
Completion removes the rest of the line

### ISSUE THREAD

**Issue by w9** [zerolfx/copilot.el#117]
If we start with the following text, where "`|`" is the cursor:

    ("|")

and start typing:

    ("H|")

The completion will delete the the rest of the line starting from the cursor, in this case the `")`

    ("H|ello, World!

This is highly undesirable especially when smartparens or lispy mode are used, and the parentheses balance are ruined.

**Comment by zerolfx** [comment]
The issue appears to be a result of Copilot, and unfortunately I have not been able to find a solution within copilot.el itself.

See also #116 #27 https://github.com/orgs/community/discussions/50038 https://github.com/orgs/community/discussions/46277
