### ISSUE TITLE
what is the `s` dependency? 

### ISSUE THREAD

**Issue by hanwen** [zerolfx/copilot.el#118]
your readme says:

## Option 2: Load manually
Please make sure you have these dependencies installed.

`dash`
`s`
`editorconfig`

dash and editorconfig ring bells to me, but what is `s` ? Can you provide a URL?

**Comment by zerolfx** [comment]
https://github.com/magnars/s.el

**Comment by hanwen** [comment]
thanks. It wasn't obvious to me that these were Emacs packages (there are 'dash' and 'editorconfig' packages in Fedora)

**Comment by rakotomandimby** [comment]
@hanwen , "packages" here, and in any Emacs related document, is referring "Emacs package" (Melpa / Elpa). Never Linux distribution package. By the way, I recommend you to remove the Fedora 'dash' and 'editorconfig' you installed with yum or dnf, and do it with Emacs package manager
