### ISSUE TITLE
completion setup with elpy and jedi?

### ISSUE THREAD

**Issue by uliw** [zerolfx/copilot.el#12]
How would one go about enabling copilot completions when using elpy and jedi? Using this combination requires that company mode is disabled

**Comment by zerolfx** [comment]
`copilot.el` has no extra dependency, and it can work together with any completion backend.

It should show completions properly after enabling `copilot-mode`.
To accept the completion, you will have to bind `copilot-accept-completion` to some key.

**Comment by uliw** [comment]
thanks. the following works for me

```elisp
(use-package copilot
  :straight (:host github :repo "zerolfx/copilot.el"
                   :files ("dist" "copilot.el"))
  :ensure t
  :bind
  ("C-x TAB" . copilot-accept-completion))
```
