### ISSUE TITLE
Sending context from recently accessed buffers

### ISSUE THREAD

**Issue by JaydenNavarro-at** [zerolfx/copilot.el#122]
From what I've read online (note: not from GitHub docs directly), the vscode copilot plugin sends the last several accessed files to copilot as additional context to provide better suggestions. This seems particularly useful when classes/types are defined in other files, as without this extra context copilot just guesses at what functions/members/properties exist on the given object.

It would be nice if this package could offer something similar, e.g. sending the buffer contents from the N most recently opened buffers (up to `copilot-max-char` characters). For safety, likely would only want to include buffers that are also in `copilot-mode` minor mode.

**Comment by zerolfx** [comment]
I have experienced the same behavior on CLion, where it suggests function definitions from other files while completing the current file.

The main challenge is that VSCode's Copilot API is not public. Therefore, `copilot.el` and other unofficial Copilot plugins rely on `copilot.vim`. If `copilot.vim` adds this functionality, `copilot.el` can also take advantage of it.

https://github.com/github/copilot.vim

**Comment by spenczar** [comment]
https://thakkarparth007.github.io/copilot-explorer/posts/copilot-internals provides some very detailed (but speculative) reverse engineering of how Copilot works. The way it works is somewhat sophisticated:

 - Gather the last 20 accessed files for the same language as the current file.
 - Find "similar snippets" from those 20 files, which is done by slicing up the files into windows and calculating the "similarity" of the slices with the file you have open (using Jaccard similarity).
  - Use a gazillion heuristics to construct a fancy prompt which uses those snippets. Like, a *lot* of heuristics.
  
There's a ton of secret sauce in there and my guess is it won't make it to the Vim plugin any time soon. I think you'd need a pretty totally different approach from the one in this project to replicate the behavior of VSCode Copilot, unfortunately - like, you'd probably end up building a prompt engineering pipeline and communicating directly with the OpenAI Codex APIs... which were deprecated last month and partially removed from public access :(

**Comment by zerolfx** [comment]
@spenczar Thanks for sharing this excellent article.

All the sophisticated work can be done in the binary (`agent.js`) file, which is transparent to plugin developer. What I can do is follow the logic in `copilot.vim` precisely and hope the functionality will be added to the `agent.js` file from `copilot.vim` soon.

**Comment by spenczar** [comment]
I've been working on repeating the work from that article, but on the current agent.js in copilot.vim. So far, it looks like it does all the same stuff. It computes Jaccard similarity for sliding windows, does tree-sitter parsing - the whole deal. So a good question is why it seems to _feel_ like it's less clever.

I think that, as it currently stands,`agent.js` builds its knowledge about other files exclusively via calls to its `textDocument/didChange` and `textDocument/didOpen`. Those are only called by `copilot--sync-doc`, which is only called as part of `copilot-complete`. So if you haven't tried a code completion in another file in the same `agent` server session, it won't be available to Copilot as context.

I haven't really been able to make sure of this, but it _seems_ like the agent can alternatively use workspaces. One little piece of evidence of this is if I manually `initialize` and tell the agent that we can describe workspace folders, it responds saying it wants to use those capabilities.

The current initialization in copilot.el specifies no client capabilities at all:
```elisp
(copilot--request 'initialize '(:capabilities 'nil))
;; evals to this response from the agent:
(:capabilities 
  (:textDocumentSync (:openClose t :change 2) 
   :workspace (:workspaceFolders (:supported :json-false :changeNotifications :json-false))))
```

But if I tell it "We can apply edits to workspaces, and we can tell you the folders that make up a workspace if you ask," we get a different answer from the agent:

```elisp
(copilot--request 'initialize 
  '(:capabilities (:workspace (:applyEdit t :workspaceFolders t :configuration t))))
;; response:
(:capabilities 
  (:textDocumentSync (:openClose t :change 2) 
   :workspace (:workspaceFolders (:supported t :changeNotifications t))))
```

I don't actually know how it uses this workspace information; the code is pretty obfuscated. It could be worth experimentation.

But a certain thing to work is to be a little more aggressive with calling `copilot--sync-doc`. I'm thinking about adding hooks to send it waaaaay more often and seeing how my suggestions change.

**Comment by zerolfx** [comment]
@spenczar The workspace option is in LSP standard.
See https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#serverCapabilities and https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspaceFeatures

For `copilot--sync-doc`, I followed the logic from `copilot.vim`, which invokes the sync each time before requesting a completion.

**Comment by spenczar** [comment]
> @spenczar The workspace option is in LSP standard.
> 
> See https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#serverCapabilities and https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspaceFeatures


Yep. I was just saying that the agent supports some workspace capabilities. An LSP server can respond that it doesn't support workspace edits or folders. There is some explicit logic for this in agent.js.

> For `copilot--sync-doc`, I followed the logic from `copilot.vim`, which invokes the sync each time before requesting a completion.

Yeah, this is reasonable if you want to keep copilot.el as a straight port of copilot.vim. If you're willing to diverge a bit though, you I think sending files more often would be helpful.
