### ISSUE TITLE
copilot-complete not automatic

### ISSUE THREAD

**Issue by james-ennis** [zerolfx/copilot.el#123]
I have copy and pasted exactly what is in the spacemacs configuration part of the [README](https://github.com/zerolfx/copilot.el#example-for-spacemacs) and looking at the [General configurations for configuring completetion](https://github.com/zerolfx/copilot.el#option-1-use-copilot-mode-to-automatically-provide-completions) all I should need is `(add-hook 'prog-mode-hook 'copilot-mode)`, which I have in my user-config. 

However, unless I explicitly run the command `copilot-complete`, I'm not getting automatic suggestions, any help would be greatly appreciated.
![Screencast from 06-04-23 16 42 22](https://user-images.githubusercontent.com/34315445/230431202-547440ae-9cdc-4352-bd62-02e3515772dd.gif)

**Comment by zerolfx** [comment]
Does setting `copilot-enable-predicates` to `nil` help?

**Comment by james-ennis** [comment]
Aha, that seems to have done it. Thank you very much. I'll do a PR which tweaks the spacemacs config
