### ISSUE TITLE
Effect of copilot-enable-predicate

### ISSUE THREAD

**Issue by rakotomandimby** [zerolfx/copilot.el#128]
Hi, this is not an issue but a question.
What is the effect of `(copilot-enable-predicate nil)` or `(copilot-enable-predicate t)`?

**Comment by kliph-gladly** [comment]
They are lists of predicate functions that are evaluated to determine the appropriate conditions for whether a Copilot completion will be created.  See https://github.com/zerolfx/copilot.el/blob/main/copilot.el#L543 .
