### ISSUE TITLE
support for huggingface starcoder

### ISSUE THREAD

**Issue by hammerandtongs** [zerolfx/copilot.el#137]
From a conversation at reddit -

https://old.reddit.com/r/emacs/comments/138f8nl/open_copilot_alternative/

> It has 15.5B parameters, 8192 context window, it was trained on permissively licensed code. 

https://huggingface.co/bigcode/starcoder

Existing VSCode extension-

https://marketplace.visualstudio.com/items?itemName=HuggingFace.huggingface-vscode

https://github.com/Soulter/hugging-chat-api

https://thakkarparth007.github.io/copilot-explorer/posts/copilot-internals.html#reverse-engineering-preview of copilot

**Comment by zerolfx** [comment]
I don't have the energy to maintain a plugin that I don't use. Additionally, I'm not using Emacs as frequently as before.

Thank you for your suggestion, and I also believe that providing more choices for Emacs users is a good thing. Furthermore, feel free to reference and use the code in copilot.el - I believe there are still some useful parts for completion display.

**Comment by danlamanna** [comment]
For those following, it looks like someone created a version here https://gitlab.com/daanturo/starhugger.el.

> I don't have the energy to maintain a plugin that I don't use. Additionally, I'm not using Emacs as frequently as before.

Thanks for being upfront about the limits of your capacity to maintain this (excellent) package.
