### ISSUE TITLE
error in process filter: Keyword argument :cancellationReason not one of (:completions)

### ISSUE THREAD

**Issue by BuddhiLW** [zerolfx/copilot.el#138]
This error is occurring every time I type, when using copilot. And it blocks the main thread of emacs. I can't type for like 5 seconds or more, at every typing.

**Comment by BuddhiLW** [comment]
The error occurs after [2014e0beb448252225773f81561ecc5ead29874a](https://github.com/zerolfx/copilot.el/commit/2014e0beb448252225773f81561ecc5ead29874a)

**Comment by maikol-solis** [comment]
Thanks for this report. I'm having the same issue. 

I'll copy your solution from the doom-emacs repo 

```lisp
(package! copilot
  :recipe (:host github :repo "zerolfx/copilot.el" :files ("*.el" "dist"))
  :pin "0160a1108b3bc3fff7e9fe1ebb67e71c0c2a334d")
```

**Comment by zerolfx** [comment]
Fixed in 1ab40d8.

**Comment by maikol-solis** [comment]
Thanks! It works perfectly. 👍

**Comment by ethansieve** [comment]
Hi, I still get this error on Emacs 29.1 and `copilot.el` commit `0d48e75dabef86b962b7a8bfcc7d3614a1201821`:
```
Error running timer: (error "Keyword argument :cancellationReason not one of (:completions)")
```
