### ISSUE TITLE
[question] Do copilot.el send feedback to Github?

### ISSUE THREAD

**Issue by rakotomandimby** [zerolfx/copilot.el#140]
I would like to know if copilot.el sends data to Github about suggestion acceptance or any other data they need.
It is OK for me, in fact I would even be happy if my data can be used to feed.

**Comment by zerolfx** [comment]
Yes. You can search these keywords in copilot.el to learn more:
- `'notifyShown`
- `'notifyRejected`
- `'notifyAccepted`
- `'setEditorInfo`
