### ISSUE TITLE
[Feature Request] Add support for Copilot chat

### ISSUE THREAD

**Issue by svenssonaxel** [zerolfx/copilot.el#141]
The [GitHub Copilot Nightly extension](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-nightly) now has support for GitHub Copilot chat private beta. It would be great if this could be added to copilot.el.

**Comment by zerolfx** [comment]
copilot.el is based on https://github.com/github/copilot.vim.
I will add this feature once it becomes available in copilot.vim.

**Comment by merlynmarc** [comment]
Thanks for the great work on this!  Was about to ask the same thing.
