### ISSUE TITLE
Copilot fails with jsonrpc-error

### ISSUE THREAD

**Issue by jheyming** [zerolfx/copilot.el#148]
Whenever I do `copilot-login` I get the following error:

Copilot agent started.
[jsonrpc] Server exited with status 1
jsonrpc-request: jsonrpc-error: "request id=1 failed:", (jsonrpc-error-code . -1), (jsonrpc-error-message . "Server died"), (jsonrpc-error-data)

Any tips?

**Comment by jheyming** [comment]
emacs-version is 28.1
node --version is v16.15.1
jsonrpc 1.0.17

**Comment by jheyming** [comment]
`copilot-diagnose` is the same:

```
Copilot agent started.
[jsonrpc] Server exited with status 1
jsonrpc-request: jsonrpc-error: "request id=1 failed:", (jsonrpc-error-code . -1), (jsonrpc-error-message . "Server died"), (jsonrpc-error-data)
```

**Comment by jheyming** [comment]
I figured it out. this is a manual install and I had to change `copilot--base-dir`

**Comment by LazerJesus** [comment]
what did you set it to and how?
