### ISSUE TITLE
emacs in non-gui mode (-nw): how to accept copilot suggestion?

### ISSUE THREAD

**Issue by cpbl** [zerolfx/copilot.el#158]
Apologies if this is off-topic or if the answer ends up being idiosyncratic, but pressing "tab", which works to accept copilot suggestions in my GUI emacs window, does not work when using Emacs with `-nw` option. Instead, it makes the suggestion go away.
 Would this happen to be something to do with the plugin??

**Comment by zerolfx** [comment]
To determine which key you pressed and the command it is bound to, use `M-x describe-key`.

**Comment by cpbl** [comment]
Oh, thank you very much. 
It says : indent-for-tab-command &optional ARG
So maybe it's possible for my settings to have different bindings for gui and non-gui emacs?

This is what's in my init.el, which makes things work in the GUI!
```
(defun my/copilot-tab ()
  (interactive)
  (or (copilot-accept-completion)
      (indent-for-tab-command)))

(with-eval-after-load 'copilot
  (define-key copilot-mode-map (kbd "<tab>") #'my/copilot-tab))

```

**Comment by zerolfx** [comment]
What is the key you pressed? I guess that it is `TAB` rather than `<tab>`.

**Comment by cpbl** [comment]
Thank you for the hint!

So :

- TAB = Ctrl-i
- <tab> is more of a virtual concept in emacs rather than a physical key. They can be mapped separately sometimes.
- (Typically?) <tab> is mapped to Ctrl-i in the GUI but not in terminal; see https://github.com/syl20bnr/spacemacs/issues/4024#issuecomment-161122099
- Changing `<tab>` to `TAB` in my init.el solves the problem
- I suggest it might make sense and be harmless to assign both keys in the default installation?

Other references:
https://stackoverflow.com/questions/26195884/tab-v-tab-in-emacs

**Comment by zerolfx** [comment]
Thanks for sharing your findings!
I also found it a bit confusing, so in the example configurations, I ended up binding both `<tab>` and `TAB`.
