### ISSUE TITLE
Docs Issue - No such file or directory editorconfig

### ISSUE THREAD

**Issue by CaptainLazarus** [zerolfx/copilot.el#162]
Issue in the docs. Need to install editorconfig before this plugin can be used. Using quelpa + quelpa-use-package on standard emacs and I got the error 

```
 No such file or directory editorconfig
```

Fixed by using

```
M-x package-install RET editorconfig RET
```

**Comment by zerolfx** [comment]
I have already declared `editorconfig` as a dependency. Shouldn't it be resolved and installed automatically?

https://github.com/zerolfx/copilot.el/blob/a68f1ce94addc45984ba5bb1972bfba95c8b7f96/copilot.el#L11

**Comment by CaptainLazarus** [comment]
That's weird. It didn't pick it up. I used quelpa for installing it and followed the docs to a T.

Using NixOS. Not sure if relevant.

**Comment by zerolfx** [comment]
Sorry, I'm not familiar with the workings of Emacs package management. 
After looking at the readmes of other packages, it seems necessary to include a list of (uncommon) dependencies in the readme file. I will add this information at a later time.

**Comment by CaptainLazarus** [comment]
Dude, you wrote the copilot plugin. You don't need to apologise. Great work btw.
