### ISSUE TITLE
The cursor moves when a suggestion is shown in typescript

### ISSUE THREAD

**Issue by GuiAmPm** [zerolfx/copilot.el#165]
Note: This issue might be due to Tide, please close it if that's the case.

Using Doom Emacs on a typescript project, sometimes I face this issue:
![Peek 2023-08-09 16-37](https://github.com/zerolfx/copilot.el/assets/9289786/2367871f-0393-4f18-9617-d4a414859c00)

Basically I start a block, when I press the closing bracket (or parens), my cursor moves one character before the closing bracket.

This usually happens when the bracket is the last character in the line and does not reproduce when there's whitespace characters after it.

And when my block looks like this `const my_block = ({ ` and I press `}` then `)` the behaviour looks like this:
![Peek 2023-08-09 16-46](https://github.com/zerolfx/copilot.el/assets/9289786/2b597ceb-6c97-432c-8eb9-8a9e98b2d3d4)

This only happens on Typescript files, while others (tested: Rust and plain text) seem to work as expected.
Turning off Copilot mode also fixes the issue.

Either way, thanks for making this project.

**Comment by dangtran47** [comment]
I got the same issue when typing parenthesis.

https://github.com/zerolfx/copilot.el/assets/49431747/0cc142b4-19d9-4b7b-8974-345088d2966a
