### ISSUE TITLE
Autoloading file copilot.elc failed to define function copilot

### ISSUE THREAD

**Issue by Kyrremann** [zerolfx/copilot.el#169]
I'm trying to set up Copilot using the following configuration, but get the following error when calling `copilot`.

```
Autoloading file /Users/kyrremann/.emacs.d/elpa/copilot-20230817.22242/copilot.elc failed to define function copilot
```

The diagnose tool returns OK.
```
Copilot agent started.
Copilot OK.
```

My configuration
```
(quelpa '(copilot :fetcher github
                   :repo "zerolfx/copilot.el"
                   :branch "main"
                   :files ("dist" "*.el")))
(use-package copilot
  :hook (add-hook 'prog-mode-hook 'copilot-mode))
  ```

**Comment by Kyrremann** [comment]
Okay, it turns out everything works. I just can't call `copilot` or `copilot-mode` in a buffer. Maybe I'm not supposed to do that?

**Comment by emil-vdw** [comment]
Also, there is no `copilot` function. Make sure the mode is active, whether you rely on the hook or activate the mode manually with `M-x copilot-mode`.

You can verify the mode is active by calling `M-x describe-mode`. Completions should appear but you can call `M-x copilot-complete` manually as well.

**Comment by Kyrremann** [comment]
Thank you, that was a silly mistake from my side. `use-package` is working, but getting 
```
Symbol's value as variable is void: copilot-completion-map
```
when I add the following below the `use-package`.
```
(define-key copilot-completion-map (kbd "<tab>") 'copilot-accept-completion)
(define-key copilot-completion-map (kbd "TAB") 'copilot-accept-completion)
```

PS: Using `:bind` in `use-package` is overriding every `tab` keybinding.
```
(use-package copilot
  :bind (("<tab>" . copilot-accept-completion)
             ("TAB" . copilot-accept-completion))
  :hook (prog-mode . copilot-mode))
```

**Comment by zerolfx** [comment]
Please read the example configurations in README.
