### ISSUE TITLE
Warning with `copilot-max-char`

### ISSUE THREAD

**Issue by maikol-solis** [zerolfx/copilot.el#175]
Every time I start doom-emacs I receive this message 

```
Warning (emacs):  *temp* size exceeds ’copilot-max-char’ (100000), copilot completions may not work [3 times]
```
It seems to be a minor issue because after closing the warning, I can use copilot correctly. 

Please let me know what I can do to further debug this.

Best.

**Comment by emil-vdw** [comment]
@maikol-solis there is a default limit (`copilot-max-char`) of 100'000 characters that is sent to the copilot agent to prevent sending super large buffers. This means that if a buffer has a size of 500'000 characters, only 1/5th of the buffer will be sent to the agent. Predictions won't work reliably in these buffers but other buffers will work just fine.

You can increase the limit (or disable it by setting it to `-1`) if the buffers you're working on are large.

In your case it looks like it's some temporary buffer `*temp*` that's exceeding the limit. I don't know if this is a doom emacs thing or just part of your setup. 

Are you using `global-copilot-mode`?

**Comment by emil-vdw** [comment]
Awesome. You could also write a more sophisticated hook function that doesn't activate the mode for certain buffer names (like `*temp*` and your agenda files).

Closing as resolved.

**Comment by forgoty** [comment]
@emil-vdw any suggestions how to disable copilot-mode at this large buffers with (global-copilot-mode)?

**Comment by mrcnski** [comment]
Is there a way to suppress the warning, or make it a message instead? For me, the issue's not critical enough to appear in the `*Warnings*` buffer. For now I'll just bump the limit. :)
