### ISSUE TITLE
Turbopilot support 

### ISSUE THREAD

**Issue by rafaelcgs10** [zerolfx/copilot.el#186]
I imagine many of us don't like to connect to a proprietary  server.

[Turbopilot ](https://github.com/ravenscroftj/turbopilot)  is a alternative that runs locally in any CPU.

Its readme says it has plans to be compatible with the copilot API.

Does this project has plans to support Turbopilot?

**Comment by rakotomandimby** [comment]
@rafaelcgs10 , I think https://www.tabnine.com/install/emacs is a more mature alternative.
Anyway, I dont think it is a good idea to be multi purpose here.
The focus on Github Copilot and only Github Copilot should be the priority.

**Comment by rakotomandimby** [comment]
BTW, we also have this: https://codeium.com/blog/codeium-copilot-alternative-in-emacs

**Comment by mikej96** [comment]
Looks like the maintainer of Turbopilot archived/deprecated the project as of 9/30/2023.
