### ISSUE TITLE
JSON RPC server died/exited

### ISSUE THREAD

**Issue by amusingimpala75** [zerolfx/copilot.el#187]
I just installed `copilot.el` but if I try to run `copilot-login` or `copilot-diagnose` all I get is the following:

macOS Ventura
Emacs 29
I have ensured that `s`, `dash`, and `editorconfig` are installed.

```
Copilot agent started.
[jsonrpc] Server exited with status 1
jsonrpc-request: jsonrpc-error: "request id=1 failed:", (jsonrpc-error-code . -1), (jsonrpc-error-message . "Server died"), (jsonrpc-error-data)
Copilot agent started.
[jsonrpc] Server exited with status 1
Error during redisplay: (copilot--on-doc-focus #<window 3 on *dashboard*>) signaled (jsonrpc-error "request id=1 failed:" (jsonrpc-error-code . -1) (jsonrpc-error-message . "Server died") (jsonrpc-error-data))
```

**Comment by amusingimpala75** [comment]
Solved because `elpaca` clones the repo into `~/.emacs.d/elpaca/repos/<name>` but the built / compiled form is in `~/.emacs.d/elpaca/build/<name>`, and thus since the location of `copilot.elc` is in the build dir, node cannot find `dist/agent.js`. Fixed by setting `copilot--base-dir` to the location of the cloned repo, both in `:init` and `:config`. Maybe only one is necessary? Issue #148 was useful in figuring this out.

**Comment by hajime-f** [comment]
I'm experiencing the same issue. Could you please explain in more detail what specific modifications were made by "Fixed by setting copilot--base-dir to the location of the cloned repo, both in :init and :config"?

**Comment by hajime-f** [comment]
@amusingimpala75 
I'm experiencing the same issue. Could you please explain in more detail what specific modifications were made by "Fixed by setting copilot--base-dir to the location of the cloned repo, both in :init and :config"?
