### ISSUE TITLE
Agent stopped working

### ISSUE THREAD

**Issue by jkbpvsc** [zerolfx/copilot.el#195]
Since last few days  the agent has stopped working.

Diagnose repeatedly outputs this
```
Copilot error: (:code 1000 :message "Not authenticated: NotAuthorized")
```

Event after successfully logging in
```
Verifying...
Authenticated as GitHub user jkbpvsc.
```

*copilot-events* just has this for me
```
----------b---y---e---b---y---e----------
[stderr] 
[stderr] 
[stderr] nil
[stderr] nil
[stderr] Process copilot agent stderr finished
[stderr] 
[stderr] 
[stderr] nil
[stderr] nil
[stderr] Process copilot agent stderr<1> finished

```

**Comment by finger563** [comment]
@jkbpvsc what was the issue with your setup? I've recently upgraded my emacs and configurations and am running into this same issue
