### ISSUE TITLE
I can't get it to work(Am I dumb?)

### ISSUE THREAD

**Issue by iljo-dp** [zerolfx/copilot.el#197]
I am running vanilla gnu emacs with the elpaca package manager. Since I don't know how elpaca works with this package I've tried to download it manually.
What I've done is this
```
  (use-package dash :ensure t)
  (use-package s :ensure t)
  (use-package editorconfig :ensure t)
  (add-to-list 'load-path "~/.config/emacs/packages/copilot.el")
  (add-to-list 'load-path "~/.config/emacs/packages/copilot-balancer.el")
  (load-file "~/.config/emacs/packages/copilot-balancer.el")
  (load-file "~/.config/emacs/packages/copilot.el")
  (require 'copilot)
  (setq copilot-node-executable "/usr/bin/node")

  (add-hook 'prog-mode-hook 'copilot-mode)

  (define-key copilot-completion-map (kbd "<tab>") 'copilot-accept-completion)
  (define-key copilot-completion-map (kbd "TAB") 'copilot-accept-completion)
```
the ~/.config/emacs/packages/... is the directory where i've git cloned the files and everything is present.

But my problem, when opening emacs after inserting this code. I get the error;
File is missing: Cannot open load file, No such file or directory, dash

Am I just stupid or can someone help?

**Comment by kliph-gladly** [comment]
Hi.  It looks like you don't have `dash` installed.  Its installation instructions are here https://github.com/magnars/dash.el#installation.  I can't help with specific instructions for how to install it via elpaca as I'm not familiar with it.
