### ISSUE TITLE
NoTelemetryConsent

### ISSUE THREAD

**Issue by mput** [zerolfx/copilot.el#2]
Hi!
I'm trying to set up the project. 
The login works as expected:
```Copilot agent started.
Verifying...
I agree to these telemetry terms as part of the GitHub Copilot technical preview.
https://github.co/copilot-telemetry-terms (y or n) y
Login success!
```
but on copilot-diagnose I receive a message like this:
```
Copilot agent: Running, Network: OK, Access: error: ((code . 1000) (message . "Not authenticated: NoTelemetryConsent"))
```

What could be the reason?

Thank you in advance.

**Comment by zerolfx** [comment]
Thanks for your feedback.

That is a bug. Could you try it again with the latest code?

**Comment by mput** [comment]
Thx! Works now. I'll start to explore.
