### ISSUE TITLE
Device Activation

### ISSUE THREAD

**Issue by tsengf** [zerolfx/copilot.el#201]
Hi, when I run copilot-login, my browser pops up and asks for my github credentials. Then I am presented with a dialog box titled Device Activation requiring me to enter an 8-character code. Where do I find the code to enter? Thanks.

**Comment by zerolfx** [comment]
Clipboard?

**Comment by tsengf** [comment]
I should mention that I'm in a linux environment. I'll check.

**Comment by henrymazza** [comment]
wow! where did it come from? ahahah

omg i was looking on my phone, now I understand the device is my computer (－‸ლ)
