### ISSUE TITLE
Way to turn autocompletion off completely

### ISSUE THREAD

**Issue by mattiuusitalo** [zerolfx/copilot.el#202]
It appears that I can't turn automatic completions off. So I'm currently doing this to make it very long which kind of disables the automatic completions:
`(setq copilot-idle-delay (* 60 60 10))`  

I propose it could be
`(setq copilot-idle-delay -1)` 

which turns the automatic completions completely off.

**Comment by zerolfx** [comment]
In your case, you may not want to enable copilot-mode. 

Also see "Option 2: Manually provide completions" section in README for reference.

**Comment by mattiuusitalo** [comment]
I see. Thanks!

**Comment by xmatos-so** [comment]
It seems to me `copilot-complete` doesn't work when `copilot-mode` is disabled. What I have done is enable `copilot-mode` and add a fn to disable predicates that always return true:

```
(add-to-list 'copilot-disable-predicates #'(lambda () t))
```

**Comment by iostapyshyn** [comment]
Experiencing same as @xmatos-so here. Should we reopen the issue?
