### ISSUE TITLE
Recent changes might have broken it.

### ISSUE THREAD

**Issue by yubrshen** [zerolfx/copilot.el#208]
I just updated copilot.el about 2 hours ago. When starting emacs as a daemon, I got the following error:
Debugger entered--Lisp error: (jsonrpc-error "request id=1 failed:" (jsonrpc-error-code . -1) (jsonrpc-error-message . "Server died") (jsonrpc-error-data))                                            signal(jsonrpc-error ("request id=1 failed:" (jsonrpc-error-code . -1) (jsonrpc-error-message . "Server died") (jsonrpc-error-data)))                                                      jsonrpc-request(#<jsonrpc-process-connection jsonrpc-process-connection-155e6998d99e> initialize (:capabilities (:workspace (:workspaceFolders t))))                                              copilot--start-agent()                                                 copilot--on-doc-focus(#<window 1 on *scratch*>)                                     copilot--mode-enter()                                                  copilot-mode()

**Comment by rakotomandimby** [comment]
@yubrshen , please check if #204 would be relevant for you.
Also, it is better to quote an extract of  the error message when reporting an issue.

**Comment by yubrshen** [comment]
Indeed, the upstream of code of JavaScript has changed the required version of node from 16x to 18x.
The version of node in mine had been 16.x, thus the server for copilot (started by node dist/agent.js) failed without any trace. 
After switching to node v18.19.0, it works now.

**Comment by VictorYYW** [comment]
Your solution is exactly what I am looking for. Thanks, @yubrshen!
