### ISSUE TITLE
feature request or question

### ISSUE THREAD

**Issue by pcompassion** [zerolfx/copilot.el#211]
It seems I can specify which mode I want copilot turned on.

Since I write up programming designs in org mode, 
I want copilot to read the org mode and use it in prog-mode. 

i.e. read-only mode for copilot (e.g. org mode) 

Thank you

**Comment by emil-vdw** [comment]
Are you wanting to enable copilot for org mode?

**Comment by emil-vdw** [comment]
If you want to configure copilot mode differently for org mode you can do something like the following:
```elisp
(defun my/org-mode-copilot ()
  "Set up copilot for org-mode."
  (copilot-mode)
  (setq-local copilot-idle-delay 100000)
 )

(use-package copilot
  ...
  :hook
  (prog-mode . copilot-mode)
  ;; Add the new org mode init function to your hooks.
  (org-mode . my/org-mode-copilot)
  ...)
```
