### ISSUE TITLE
New warning basically breaks copilot.el

### ISSUE THREAD

**Issue by Ramblurr** [zerolfx/copilot.el#214]
![image](https://github.com/zerolfx/copilot.el/assets/14830/4390e6a1-5cc0-415b-ba47-7acd2f50abdc)

This new warning that is displayed upon every keypress is rather frustrating.

1. It is displayed on every keypress
2. It does not contain (nor the docs here on github) any actionable instructions

This renders copilot.el effectively useless and the warning is basically a fatal error because I can't use emacs with it enabled.

If its just a warning (i.e., a non fatal error that can be ignored) it shouldn't display on every keystroke.

And ideally there would be some actionable advice or documentation about how to resolve the warning/error.

**Comment by zerolfx** [comment]
@blahgeek Please help with the issue here since it's related to #212.

**Comment by Ramblurr** [comment]
@zerolfx Ah yea I saw that, but it was closed so I opened a new one.

**Comment by Ramblurr** [comment]
Done! Feel free to delete this one if you want.
