### ISSUE TITLE
browse-url-select-handler: Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by Azizul7m** [zerolfx/copilot.el#22]
**copilot.el** It's the first time that I'm getting this error. Suddenly, I have to shift my new machine and I want to login in **copilot.el** by `copilot-login`. this is the error 

`browse-url-select-handler: Wrong type argument: stringp, nil`

But everything works fine 🤩 (All the completions).

![Image](https://i.imgur.com/lIov0n7.png)

**Comment by zerolfx** [comment]
Please trigger this error again and attach related logs in `*copilot events*` buffer.

**Comment by zerolfx** [comment]
fixed
