### ISSUE TITLE
cl-no-applicable-method: No applicable method: jsonrpc--request-continuations, nil

### ISSUE THREAD

**Issue by maurelio1234** [zerolfx/copilot.el#25]
Follows discussion here: https://github.com/zerolfx/copilot.el/issues/21

For information:

OS: MacOS
Build options: `"--with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules"`
Emacs: 28.1

Configuration:

```(use-package copilot
  :straight (:host github :repo "zerolfx/copilot.el"
                   :branch "main")
  :custom
  (copilot-node-executable "/Users/Marcos/.nvm/versions/node/v17.9.1/bin/node"))
```

>  Also, please attach relative stuff in *Message*, *copilot stderr* and *copilot event*?

I just have one line of error with:

> cl-no-applicable-method: No applicable method: jsonrpc--request-continuations, nil

on  `*Message*`. The other buffers do not exist.

**Comment by zerolfx** [comment]
It is a bug. 
Copilot agent doesn't automatically start if you call `copilot-login` before enabling `copilot-mode`.

**Comment by zerolfx** [comment]
Fixed.

Because only `copilot-mode` is auto-loaded, so usually `copilot-login` is unavailable before enabling `copilot-mode`. It's an edge case :)

**Comment by maurelio1234** [comment]
Hmm it's better than before, but now I have this on `*copilot events*`: 

```[client-request] (id:1) Sun Jun 12 10:02:12 2022:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
          (:capabilities 'nil))
[stderr] node:internal/modules/cjs/loader:936
[stderr]   throw err;
[stderr]   ^
[stderr] 
[stderr] Error: Cannot find module '/Users/Marcos/.emacs.d/straight/build/copilot/dist/agent.js'
[stderr]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[stderr]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[stderr]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
[stderr]     at node:internal/main/run_main_module:17:47 {
[stderr]   code: 'MODULE_NOT_FOUND',
[stderr]   requireStack: []
[stderr] }
[stderr] 
[stderr] Node.js v17.9.1
[internal] Sun Jun 12 10:02:12 2022:
(:message "Connection state changed" :change "exited abnormally with code 1\n")

----------b---y---e---b---y---e----------
```

And this on `* Messages * `

```jsonrpc-request: jsonrpc-error: "request id=1 failed:", (jsonrpc-error-code . -1), (jsonrpc-error-message . "Server died"), (jsonrpc-error-data)```

**Comment by maurelio1234** [comment]
It seems to be an incompatibility with `straight`, since the js file exists but on `  /Users/Marcos/.emacs.d/straight/repos/copilot.el/dist`

**Comment by maurelio1234** [comment]
I changed the const:

```(defconst copilot--base-dir
  "/Users/Marcos/.emacs.d/straight/repos/copilot.el"
  "Directory containing this file.")
```

And now it starts and I can login.
Afterwards it seems to work fine.

**Comment by maurelio1234** [comment]
Ok... I see that if I configure as explained on the docs I have no problems ;) Thanks for the fix anyway!

**Comment by i-am-the-slime** [comment]
I copy-pasted the instructions (for Spacemacs) and I get exactly: "No applicable method: jsonrpc--request-continuations"
Also after doing `copilot-mode`.

**Comment by zerolfx** [comment]
See #23 #34
