### ISSUE TITLE
Visual cursor jumps to end of completion while real position stays put

### ISSUE THREAD

**Issue by jimeh** [zerolfx/copilot.el#28]
Ever since commit dfa803e757d357b08d1702093abd1362287c1e73 I'm afraid I've had issues with the cursor position.

Physically, the position does not change, and any cursor movement/editing actions briefly show the cursor in the correct position again, until a copilot suggestion appears. However it only happens for single-line suggestions from copilot. If it's suggesting multiple lines, the visual cursor position stays in the right place.

Here's a couple of gifs:

On commit 56b7d1b4cff6b966ca7125b1678438097ea63050 (latest):

![copilot-current](https://user-images.githubusercontent.com/39563/174145364-4159345c-0504-40bc-9eb6-a9e24ccdd099.gif)

On commit 3dcf2a74eaa3d08c3cf30b3b24ac93ae4b40be90 with `copilot-overlay-safe` set to `nil`:

![copilot-old](https://user-images.githubusercontent.com/39563/174145455-b6365111-97dc-43f2-a85d-45580c3b30c2.gif)

**Comment by zerolfx** [comment]
The `cursor` property of the completion text does not work in your case.

The overlay thing is super easy to conflict with other plugins. I gave up the old approach (`copilot-overlay-safe` = `nil`) because of its compatibility. 

Now the newer method seems not a perfect solution. Can you try to reproduce it with a minimal setup? So I can try to fix the compatibility issue. If I fail to fix it, I will provide an option to for these two approaches.

**Comment by jimeh** [comment]
Sure thing, I'll narrow it down to a minimal setup this weekend :)

**Comment by jimeh** [comment]
That didn't take long to find. First thing I tried was disabling `whitespace-mode`, and that was culprit.

**Comment by zerolfx** [comment]
I guess removing `newline-mark` in your `whitespace-style` will solve the problem.

**Comment by jimeh** [comment]
Removing `newline-mark` did indeed solve the issue for me.

Not sure if you'd consider that a solution or a workaround though, so I'll let you choose if you want to close this issue or not.

Thanks again for your help, and continued support for copilot.el :)

**Comment by zerolfx** [comment]
I decided to leave it unsolved for now. Figuring out the logic behind overlay and cursor is a pain for me.

The overlay part now is essentially the same as https://github.com/auto-complete/auto-complete/blob/master/auto-complete.el#L927, and I assume it is good enough for general use cases.

**Comment by asmeurer** [comment]
I'm also having this issue, particularly when the completion involves a newline. I am not using whitespace-mode, and in fact I can reproduce it with a minimal configuration only enabling copilot-mode in `emacs -Q`. 

Here's a minimal reproducer:

```elisp
;; test.el
(package-initialize)

;; straight.el initialization
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))

;; Location of my use-package git clone
(add-to-list 'load-path "~/Documents/use-package")
(require 'use-package)

(use-package copilot
  :straight (:host github :repo "zerolfx/copilot.el" :files ("dist" "*.el"))
  :ensure t)

(add-hook 'prog-mode-hook 'copilot-mode)
```

Then running:

```
emacs -Q -l test.el test.py
```

and typing

```py
def test():
```

The completion looks like:

<img width="183" alt="Screen Shot 2023-04-20 at 1 31 54 PM" src="https://user-images.githubusercontent.com/71486/233469312-b7dfcf41-1820-4900-8e01-dbbd6e6c2466.png">

Note that it shows the cursor at the end of the completion but it isn't really there. If I start typing more stuff the cursor is still at the `:` in the `def test():` line. Needless to say, I find this behavior to be very disorienting.

**Comment by JiaweiChenC** [comment]
I also found the issue is still there with whitespace-mode disabled, does anyone have a temp solution for that?
