### ISSUE TITLE
Using with remote files

### ISSUE THREAD

**Issue by dangom** [zerolfx/copilot.el#29]
Hi,

thank you so much for putting this together and sharing.
If I start emacs and open a remote file via Tramp, copilot.el complaints it does not find node. I assume it is because it's looking for the node executable on the remote machine (via locate-file).
Would setting `default-directory` to `~ ` within `copilot--start-agent` cause any problems, or do you think that'd be an appropriate solution for this issue?

Thank you

**Comment by zerolfx** [comment]
I tried to fix it by changing `shell-command-to-string` to `call-process`. Hope it works for you.

**Comment by dangom** [comment]
Thank you for the quick reply.
Seems fixed!
