### ISSUE TITLE
Provide a public way to test if the overlayed suggestion is being showned

### ISSUE THREAD

**Issue by daanturo** [zerolfx/copilot.el#30]
There are many copilot commands that only make sense when the overlay is active.

I bind them in `copilot-mode-map` using `menu-item` while preventing them from overriding other keys unless the overlay is active with a filter function.

```elisp
(defun my-copilot-filter (cmd)
  (and copilot--overlay
       cmd))

(general-define-key
 :keymaps 'copilot-mode-map
 "TAB" `(menu-item "" copilot-accept-completion :filter my-copilot-filter)
 "C-g" `(menu-item "" copilot-clear-overlay :filter my-copilot-filter)
 "M-f" `(menu-item "" copilot-accept-completion-by-word :filter my-copilot-filter)
 "C-e" `(menu-item "" copilot-accept-completion-by-line :filter my-copilot-filter)

 ;; 
 )
```

It would be safer it `copilot.el` provided a public way to check if the overlay is being showed instead of making use of the internal variable as above. Such as

```elisp
(defun copilot-active-overlay-p ()
  (and copilot--overlay
       t))
```
Edit: also, exposing the suggestion string is cool, too! It can also fulfill the feature request.
```elisp
(defun copilot-current-suggestion ()
  (and copilot--overlay
       (overlay-get copilot--overlay 'completion)))
```

**Comment by zerolfx** [comment]
Thanks for your suggestion!

**Comment by daanturo** [comment]
@zerolfx thank you. There's a typo in the new function's name: `copilot-current-completEion`.

**Comment by zerolfx** [comment]
Thank you for pointing it out.
