### ISSUE TITLE
Dismissing a suggestion at the end of buffer leaves extra empty lines

### ISSUE THREAD

**Issue by knu** [zerolfx/copilot.el#36]
First of all, thank you for this amazing package!

Steps to reproduce:

1. Open an empty file `test.el` with global-copilot-mode enabled
2. Type something like `(defun test () nil)` and press Enter
3. You'll see a suggestion like `(defun test2 () nil)`.
4. Dismiss it by hitting C-g or going back to the first line
5. Save the buffer
6. You can see the saved file has an empty line at the end.

I understand that you need to add empty lines at the step 3 for a suggestion to be shown, so I'm just wondering if it is possible to remove them when the suggestion is dismissed.

**Comment by zerolfx** [comment]
Workaround: use https://github.com/lewang/ws-butler

I will try to fix it later.

**Comment by Rogach** [comment]
It seems that the problem comes from these lines:

```elisp
    (if (= (line-end-position line) (1- (point-max)))
        ; special case if the last line is empty
        (progn
          (goto-char (point-max))
          (newline)
          (forward-char -1))
      (forward-line line)
      (forward-char col))
```

Do we actually need this special case? I tested removing it and everything worked fine for me:

```diff
@@ -389,14 +389,8 @@ USER-POS is the cursor position (for verification only)."
   (save-excursion
     (widen)
     (goto-char (point-min))
-    (if (= (line-end-position line) (1- (point-max)))
-        ; special case if the last line is empty
-        (progn
-          (goto-char (point-max))
-          (newline)
-          (forward-char -1))
-      (forward-line line)
-      (forward-char col))
+    (forward-line line)
+    (forward-char col)
 
     ; remove common prefix
     (let* ((cur-line (s-chop-suffix "\n" (or (thing-at-point 'line) "")))
```

(my Emacs version is 30.0.50)

**Comment by zerolfx** [comment]
@Rogach Patch applied. Thanks for your elegant solution!
