### ISSUE TITLE
Copilot-login: Failed to get user info

### ISSUE THREAD

**Issue by goncalvesnelson** [zerolfx/copilot.el#4]
Hi! Thank you for your work with this package.

I was trying to use this package, but I am hitting an issue when running the `copilot-login` command.
I invoke the command, am given the 8 letter code, input it into the browser, come back to the editor and accept the telemetry-terms and then it fails with the following error:
```Copilot: Authenticated as GitHub user Failed to get user info.```

If I run `copilot-diagnose`  after it fails I get the following error:
```
Copilot agent: Running, Network: Server connectivity error, Access: OK
```
But then, if I run it again it returns:
```
Copilot agent: Running, Network: OK, Access: OK
```
And it will return that every time except the first time after it fails the `copilot-login` command. 

Below is the output from the `*Messages*` buffer:
```
Copilot agent: Running, Network: OK, Access: OK [2 times]
Verifying...
I agree to these telemetry terms as part of the GitHub Copilot technical preview.
https://github.co/copilot-telemetry-terms (y or n) y
Failed to get user info.
Copilot: Authenticated as GitHub user Failed to get user info.
Copilot agent output buffer reset.
Copilot agent: Running, Network: Server connectivity error, Access: OK
Copilot agent: Running, Network: OK, Access: OK
```

**Comment by nasyxx** [comment]
Same here.

**Comment by zerolfx** [comment]
I added a logger to record error messages.
Can you try again and check is there any related `[ERROR]` in the `*copilot-log*` buffer?
