### ISSUE TITLE
Tab does not indent after using configuration recomended in readme (doom emacs)

### ISSUE THREAD

**Issue by Eloitor** [zerolfx/copilot.el#40]
I use doom emacs. After modifying my config.el with the recomendation of this readme:
https://github.com/zerolfx/copilot.el/blob/9b13478720581580a045ac76ad68be075466a963/readme.md?plain=1#L38-L41
I can't use tab to indent.
This worked for me:
```
(defun my-tab ()
  (interactive)
    (or (copilot-accept-completion)
        (or (company-indent-or-complete-common nil) (indent-for-tab-command))))
```

**Comment by zerolfx** [comment]
Thanks for your suggestion! I will update the readme.

Can you also test the following config?

```elisp
(use-package! copilot
  :hook (prog-mode . copilot-mode)
  :bind (("C-TAB" . 'copilot-accept-completion-by-word)
         ("C-<tab>" . 'copilot-accept-completion-by-word)
         :map copilot-completion-map
         ("<tab>" . 'copilot-accept-completion)
         ("TAB" . 'copilot-accept-completion)))
```

**Comment by Eloitor** [comment]
It works, but I don't know what is the difference with https://github.com/zerolfx/copilot.el/blob/9b13478720581580a045ac76ad68be075466a963/readme.md?plain=1#L43-L52

**Comment by zerolfx** [comment]
See #31 

I found the overlay keymap works well for me except in `emacs-lisp-mode`. Anyway, it is a cleaner method and I will update the readme to use it.

**Comment by FlySlime** [comment]
For some reason, using the config provided by the README still doesn't work. I just downloaded this package the other day and noticed that I couldn't complete code within parentheses.

Example:
```py
if len(sys.argv)
```
Pressing TAB there would result in
```py
if len(sys.argv    )
```

However using the following config, it worked as shown in the [example GIF](https://github.com/zerolfx/copilot.el/blob/main/assets/demo.gif) provided in the README.
```elisp
;; accept completion from copilot and fallback to company
(defun my-tab ()
  (interactive)
    (or (copilot-accept-completion)
        (indent-for-tab-command)))

(use-package! copilot
  :hook (prog-mode . copilot-mode)
  :bind (("C-TAB" . 'copilot-accept-completion-by-word)
         ("C-<tab>" . 'copilot-accept-completion-by-word)
         :map company-active-map
         ("<tab>" . 'my-tab)
         ("TAB" . 'my-tab)
         :map company-mode-map
         ("<tab>" . 'my-tab)
         ("TAB" . 'my-tab)))
```

It's ugly code though, so bumping this issue so you guys can check it out hehe.

**Comment by Eloitor** [comment]
I don't use emacs anymore. I hope someone else can review your code :)
