### ISSUE TITLE
Different suggestions for neovim and copilot.el ?

### ISSUE THREAD

**Issue by jkbjh** [zerolfx/copilot.el#50]
Thanks for copilot.el, nice to be able to try this out in emacs.

I'm experiencing some interesting behaviour comparing completions in neovim vs. copilot.el;
with the following code in neovim I get ten different solutions while copilot.el gives me a single one.

```
import jax
import haiku as hk

class Auto
```
(Completing after "Auto")

Is this an expected behaviour?

**Comment by zerolfx** [comment]
(Please update copilot.el, there is a related fix.)

Have you tried `copilot-next-completion`? I could get two or three solutions in this way.

How did you get those ten solutions? If it was by opening a side panel, I would say it is an unimplemented feature.

**Comment by jkbjh** [comment]
Yes, the ten solutions was with `:Copilot panel` in neovim. 
However, I still get only one completion;
I also see
```
(:jsonrpc "2.0" :method "LogMessage" :params
	  (:level 1 :message "[INFO] [post-insertion] [2022-08-13T16:06:55.042Z] Could not get document for /tmp/test2.py. Maybe it was closed by the editor." :metadataStr "[INFO] [post-insertion] [2022-08-13T16:06:55.042Z]" :extra
		  ["Could not get document for /tmp/test2.py. Maybe it was closed by the editor."]))
```
in the `*copilot events*, maybe this is related?

To update I've executed `straight-pull-package` for copilot, and also checked the repository in `~/.emacs.d/straight/repos/copilot.el`.

Emacs version is Emacs 27.1.

**Comment by zerolfx** [comment]
The side panel feature is the only missing feature compared to `copilot.vim`, but I have no plan to implement it.

I believe you can cycle solutions via `copilot-next-completion` or it will tell you only one completion is available.
![Aug-13-2022 13-43-41](https://user-images.githubusercontent.com/20219056/184510175-14a4ffd4-9992-4665-a447-ecb37d289565.gif)

**Comment by zerolfx** [comment]
I investigated that log before, but I found `copilot.vim` had similar log messages, so I think it's okay.

**Comment by jkbjh** [comment]
Sometimes there are more completions available, then `copilot-next-completion` works for me.
for this minimal snippet
```
import jax
import haiku as hk

class Autoencoder
```
cycling through completions in nvim gives me three variants, copilot.el only one.


For your example,
```
import jax
import haiku as hk

class S
```
both nvim and copilot.el give two completions each, but *different* ones. 
Quite interesting.

Now I retried it with copilot.el five minutes later and I'm back to getting only one.

**Comment by zerolfx** [comment]
I observed the same behavior.

You can examine the `*copilot events*` buffer, especially `getCompletionsCycling` requests and corresponding responses. I think the requests are the same, but Copilot gives different results.

**Comment by jkbjh** [comment]
Interesting, then this is probably just how copilot currently works.
