### ISSUE TITLE
emacs hangs, while dismissing a copilot suggestion

### ISSUE THREAD

**Issue by yubrshen** [zerolfx/copilot.el#51]
I guess this might be related to copilot.el,, as the emacs would hang, at least twice when I press ESC to reject the suggestions from the copilot.  Since the emacs hanged, I have no means to further investigate. 

Please let me know how I can investigate further if it's related to copilot.el

I disabled the copilot by M-x copilot-mode for the same buffer/file. 
At the same file location, I no longer see the problem.

**Comment by zerolfx** [comment]
To dismiss a suggestion, you can use the `copilot-clear-overlay` command, or just keep typing.

For the freeze problem, you can use built-in [profiling](https://www.gnu.org/software/emacs/manual/html_node/elisp/Profiling.html):

1. start the profiler
2. try something and freeze Emacs
3. press `C-g` multiple times
4. stop the profiler and check the report
