### ISSUE TITLE
Can't turn off copilot globally

### ISSUE THREAD

**Issue by FlySlime** [zerolfx/copilot.el#58]
The following piece of code doesn't turn off copilot globally. I'd like to be able to enable it whenever I need it, not have it constantly on.

```elisp
;; enable copilot manually
(after! copilot
  (global-copilot-mode -1))
```

The expected output should be that the minor mode is turned off for every buffer, however this is not the case.

**Comment by zerolfx** [comment]
You can use `copilot-mode` to manually enable it, and there is nothing to do with `global-copilot-mode`.

I guess you copied the example configurations, so you need to delete the hook, such as `:hook (prog-mode . copilot-mode)`.

**Comment by FlySlime** [comment]
Wow I have no idea how I missed that lol. Changed it to ``:after copilot`` and now it is disabled by default.

Thanks.
