### ISSUE TITLE
Installation issues on mac

### ISSUE THREAD

**Issue by frmsaul** [zerolfx/copilot.el#61]
I cannot find the package on `melpa`

Do you know what the corresponding command for the github package archive?
`(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)`
 
This is the version of emacs i'm using:
<img width="829" alt="Screen Shot 2022-10-18 at 11 08 08 PM" src="https://user-images.githubusercontent.com/5913208/196610282-a7119eb2-b3a9-4cd9-bea2-545d51856945.png">

**Comment by zerolfx** [comment]
I have no plan to submit this plugin to MELPA (due to potential copyright problems).

I mentioned two ways to load copilot.el in the first section of [General Configurations](https://github.com/zerolfx/copilot.el#general-configurations).
