### ISSUE TITLE
copilot.el clobbering parens with suggestions

### ISSUE THREAD

**Issue by jjtolton** [zerolfx/copilot.el#62]
First of all -- AMAZING!  If this is something I can dive in with, happy to if you can point me in the right direction.

The issue is effectively that autocomplete is clobbering parenthesis.  Please see the GIF.  

![clobbered](https://user-images.githubusercontent.com/10394611/199578166-6a57fe7f-90b3-40ae-8c87-d112ab922c0c.gif)

It's a minor nuisance but it does break stride.

**Comment by jjtolton** [comment]
Ok still working on this a bit because it's tricky but I have something that for lisp-languages at least makes it paredit/lispy safe (meaning, the parens will be BALANCED after insertion -- not necessarily perfect) but it won't ruin your life.

![beforeFix](https://user-images.githubusercontent.com/10394611/200082804-a901a7c3-861f-4f6c-9632-213892fef1cb.gif)
![afterFix](https://user-images.githubusercontent.com/10394611/200082805-1d33f96b-14d9-40de-90f1-e17acabe85e7.gif)

No external dependencies.  Funny enough I have no idea how to write elisp, but I `copilot.el` helped me write it! (this also takes into account double quoted strings and skips over them)  :1st_place_medal:  Great stuff!

Would love to start a conversation about whether or not this is a good experience or if I should just keep it local. 

I was looking into some more sophisticated libraries to see how the approach alternate grammars and it looks like quite a lot of work: 
![image](https://user-images.githubusercontent.com/10394611/200083062-6b9082d7-7940-4e78-aed6-d35798da819a.png)

This is an example from the [`expand-region.el`](https://github.com/magnars/expand-region.el) library which handles syntax highlight for a number of grammars, and it looks pretty modular.  I don't know how much of an issue this outside of lispy languages where breaking the parenthetical grouping is devastating to the structural editing workflow.  

For the record, I tested this on JetBrains's copilot plugin, and they have the same paren clobbering issue that `copilot.el` does.

**Comment by zerolfx** [comment]
See #27. It's a known issue based on the nature of Copilot, and we don't have a perfect solution yet.

**Comment by jjtolton** [comment]
My fix works for me, so I'm closing this.  Thanks again for this amazing, amazing tool.
