### ISSUE TITLE
copilot-login jsonrpc error: Invalid params: must be object

### ISSUE THREAD

**Issue by sandersn** [zerolfx/copilot.el#63]
Very similar to #34, except with newer versions. When I run `copilot-login`, I see the following error in Messages:

`jsonrpc-request: jsonrpc-error: "request id=3 failed:", (jsonrpc-error-code . -32602), (jsonrpc-error-message . "Invalid params:  must be object"), (jsonrpc-error-data)`

- emacs 28.1
- s 1.13.1
- dash 2.19.1
- editorconfig 0.9.1
- jsonrpc 1.0.15

I cloned copilot and set it up manually. When I open a typescript buffer, `*copilot-events*` gets created, and I can see node 16 running copilot/dist/agent.js.
I tried to debug it by inserting  `message` calls in copilot.el and jsonrpc, and confirmed that the `(:jsonrpc "2.0" :id 3 :method "signInInitiate" :params 'nil)` gets converted to JSON: `{"jsonrpc":"2.0","id":4,"method":"signInInitiate","params":["quote",null]}`. Which looks plausibly correct.

My next step after filing this bug is to download jsonrpc 1.0.14 and see what changed. Maybe handling of `'nil` ?

From .emacs:
```elisp
(load-file "~/.emacs.d/lisp/copilot/copilot.el")
(require 'copilot)
;; current version doesn't work with node 18
(setq copilot-node-executable "/home/nathansa/.nvm/versions/node/v16.15.1/bin/node")
(add-hook 'typescript-mode-hook 'copilot-mode)
(customize-set-variable 'copilot-enable-predicates '(evil-insert-state-p))
;; later ...
(add-hook 'typescript-mode-hook
          (lambda ()
            (tide-setup) ; required
;; lots of tide setup omitted, let me know if it would be helpful...
            (define-key tide-mode-map (kbd "C-,") 'copilot-accept-completion)
            (company-mode))) ; required
```

From `*copilot-events*`:

```
(:jsonrpc "2.0" :id 2 :method "setEditorInfo" :params
          (:editorInfo
           (:name "Emacs" :version "28.1")
           :editorPluginInfo
           (:name "copilot.el" :version "0.9.7")))
[client-request] (id:3) Fri Nov 11 16:10:15 2022:
(:jsonrpc "2.0" :id 3 :method "signInInitiate" :params 'nil)
[server-notification] Fri Nov 11 16:10:15 2022:
(:jsonrpc "2.0" :method "LogMessage" :params
          (:level 0 :message "[DEBUG] [agent] [2022-11-12T00:10:15.343Z] Telemetry initialized" :metadataStr "[DEBUG] [agent] [2022-11-12T00:10:15.343Z]" :extra
                  ["Telemetry initialized"]))
[server-reply] (id:2) Fri Nov 11 16:10:15 2022:
(:jsonrpc "2.0" :id 2 :result "OK")
[server-reply] (id:3) ERROR Fri Nov 11 16:10:15 2022:
(:jsonrpc "2.0" :id 3 :error
          (:code -32602 :message "Invalid params:  must be object"))
```

From `*messages*`

```
(vscode-wasm-typescript-055c507e12) Starting tsserver...
(vscode-wasm-typescript-055c507e12) tsserver server started successfully.
Company backend ’company-eclim’ could not be initialized:
Symbol’s function definition is void: company-eclim
Quit [4 times]
Making completion list...
Copilot agent started.
jsonrpc-request: jsonrpc-error: "request id=3 failed:", (jsonrpc-error-code . -32602), (jsonrpc-error-message . "Invalid params:  must be object"), (jsonrpc-error-data)
```

**Comment by sandersn** [comment]
There are very few differences between jsonrpc 1.0.14 and 15:
initialize-instance uses a different method of marking some buffer readonly (probably the events buffer?), and jsonrpc-events-buffer more obviously returns the current buffer than before.

There are a couple of formatting changes.

So I don't think the difference between 1.0.14 and 1.0.15 explains anything.

**Comment by zerolfx** [comment]
Very similar to #38. I still have no idea about it.

**Comment by sandersn** [comment]
OK, I thought `''nil` -> `["quote", null]` seemed wrong. It is supposed to be `["{}"]` or `[{}]` ?

**Comment by sandersn** [comment]
Workaround: looks like you can add extra parameters to a request, so I got an object to emit by changing `''nil` to `'(:dummy 0)`
