### ISSUE TITLE
Copilot Explain Code

### ISSUE THREAD

**Issue by reachtarunhere** [zerolfx/copilot.el#66]
First of all thank you for the awesome work with the plugin!

I was wondering if there are any plans to add the code explanation feature of copilot which gives natural language explanation of part of the selected code.

Example Here: https://dev.to/github/understand-your-code-using-github-copilot-5375

**Comment by zerolfx** [comment]
It is possible only when [copilot.vim](https://github.com/github/copilot.vim) supports it.
