### ISSUE TITLE
Manual invocation on Copilot?

### ISSUE THREAD

**Issue by NightMachinery** [zerolfx/copilot.el#69]
I like to trigger generating a completion myself, and do not want to use Copilot as "autocomplete." (Because even normal company-mode makes emacs too laggy and slow.) Is that supported?

**Comment by zerolfx** [comment]
Yes. 

Please see “General Configurations” part in the readme.

**Comment by finalclass** [comment]
This is what I'm using:

```elisp
(add-hook 'post-command-hook #'copilot-clear-overlay)
(global-set-key (kbd "C-,") 'copilot-complete)
(define-key copilot-completion-map (kbd "C-.") 'copilot-accept-completion)
```
