### ISSUE TITLE
copilot clobbers closing parentheses when there is only 1 character left

### ISSUE THREAD

**Issue by LemonBreezes** [zerolfx/copilot.el#77]
Hello. With the current code, if I am writing Lisp code, copilot offers an autocompletion of 't' and I type the character 't', the rest of the line including closing delimiters is deleted. It would be helpful if we could turn off this "autocompletion of the last character" behavior.

**Comment by zerolfx** [comment]
Could you provide a detailed example, like what is on your screen before and after typing 't'? It would be better if you could record an GIF.

**Comment by LemonBreezes** [comment]
> Could you provide a detailed example, like what is on your screen before and after typing 't'? It would be better if you could record an GIF.

Sure. I just recorded a rudimentary example with my phone (not sure how to make a GIF).https://user-images.githubusercontent.com/29102529/211169968-23de18b6-c32f-4870-9a4d-e98611ff734e.mp4

**Comment by zerolfx** [comment]
Fixed.  The issue was introduced in #73.
