### ISSUE TITLE
copilot-login failed - [jsonrpc] Server exited with status 1

### ISSUE THREAD

**Issue by achisholm** [zerolfx/copilot.el#81]
I encountered the following error after setting up copilot.el in my emacs config and entering `M-x copilot-login`

Messages log:
```
Copilot agent started.
[jsonrpc] Server exited with status 1
jsonrpc-request: jsonrpc-error: "request id=1 failed:", (jsonrpc-error-code . -1), (jsonrpc-error-message . "Server died"), (jsonrpc-error-data)
Error running timer ‘copilot--post-command-debounce’: (error "Process copilot agent not running: exited abnormally with code 1
")
```

Environment details:
macOS: 13.0
emacs: v30.0.50
jsonrpc: v1.0.16
nodejs: v19.4.0
editorconfig: v0.9.1
dash: v2.19.1
s: v20220902.1511

**Comment by zerolfx** [comment]
+ Do you have NodeJS installed?
+ Try to run `node /path/to/plugin/dist/agent.js`.
+ Check buffer `*copilot stderr*` if it exists.

**Comment by achisholm** [comment]
Closing since I took the manual install route and didn't pull in the dist dir. Now resolved, up and running, thanks.
