### ISSUE TITLE
Enable sponsorships

### ISSUE THREAD

**Issue by worldofgeese** [zerolfx/copilot.el#91]
Would love to contribute to this oh-so-important package monetarily!

**Comment by ryankhart** [comment]
Agreed with this sentiment, but I think it would be even better if Microsoft/GitHub would throw their money in and offer to make this an official Emacs package for their service.

**Comment by zerolfx** [comment]
Thank you all for endorsing copilot.el.

Because this project is based on proprietary software, I don't want to make money from it.
As long as I remain an active Emacs user, I will keep maintaining this project.

@ryankhart Yes, I am also looking forward to the official copilot support for Emacs.
