### ISSUE TITLE
Tab complete over multiple lines?

### ISSUE THREAD

**Issue by ekg** [zerolfx/copilot.el#94]
What completion option will include multiple lines?

I'm only getting completions suggested to the current end of line. Looking at the demo it seems I'm missing something obvious. 

I used this method to set up tab completions: https://github.com/zerolfx/copilot.el#example-of-defining-tab-in-copilot-mode

**Comment by ekg** [comment]
Maybe I should be using company mode?

**Comment by zerolfx** [comment]
company-mode is not required, and copilot.el should able to work without any auto-completion framework.

Did you mix up `copilot-accept-completion` and `copilot-accept-completion-by-line`.

**Comment by ryankhart** [comment]
Do you see the copilot overlay showing multiple lines but you can't accept that completion except for line by line?

Or does the overlay only show line by line as well?

If it's the first scenario, that sounds more like the behavior I'd expect from `copilot-accept-completion-by-line`.

If it's the latter, I've never encountered that myself all the time, but occasionally, all copilot has to offer me is a single line anyway. For the sake of testing to rule the possibility that it's just a coincidence, maybe you could try typing in your Elisp config, something like
```
(use-pa
```
(assuming you have `use-package` installed) to see if it'll overlay a multi-line completion to that. This was my goto test when I had copilot issues.

**Comment by roysc** [comment]
This may be resolved by https://github.com/orgs/community/discussions/40522#discussioncomment-6350781, though it's not clear to me how to configure this in the package.

**Comment by gleitz** [comment]
I'm also running into this issue. I used to get multiline completions. I pulled the latest code and now I only get single-line completions. If I use `copilot-panel-complete` I can see that the suggestions contain completions that are multiple lines, but for some reason I only get the first line suggested in the overlay. 

Here is an example of a single line completion I see. I start to type "ask for french" after an existing test that uses "ask for german"

<img width="569" alt="Screenshot 2023-07-24 at 8 15 57 PM" src="https://github.com/zerolfx/copilot.el/assets/395254/7dcab400-1f39-4e01-8d74-ef81171351d8">

In the past (circa ~1 month ago) I would get a multi-line completion here, but instead I only see one line of suggestion and have to accept completions line by line. 

When using `copilot-panel-complete` I can see that the rest of the multi-line completion is there, so it's strange to make that I only get one line of the suggested multi-line answer.

<img width="668" alt="Screenshot 2023-07-24 at 8 16 04 PM" src="https://github.com/zerolfx/copilot.el/assets/395254/30ba13b4-cb15-4810-8307-95da9ae59003">

**Comment by zerolfx** [comment]
@gleitz `copilot-panel-complete` uses another API. For detailed requests and responses, please see `*copilot events*` buffer.

**Comment by gleitz** [comment]
Ah, that's good to know. Sorry if this is a dumb question but I set `copilot-log-max` to nil but I don't see a `*copilot events*` buffer. Is there another way to access logs?

**Comment by gleitz** [comment]
OK, I can confirm that the completion coming back from Copilot only contains the single line. Here is the result of the `"ask for french"` with a completion of `, async () => {`.

```
[server-reply] (id:111) Mon Jul 24 21:56:58 2023:
(:jsonrpc "2.0" :id 111 :result
          (:completions
           [(:uuid "3f2dae10-f3b4-42e3-b07c-81fdc7d906d9" :text "  test(\"ask for french\", async () => {" :range
                   (:start
                    (:line 102 :character 0)
                    :end
                    (:line 102 :character 23))
                   :displayText ", async () => {" :position
                   (:line 102 :character 23)
                   :docVersion 133)]))
```

I also wonder, like @roysc , if this is related to the [github issue]( https://github.com/orgs/community/discussions/40522#discussioncomment-6350781). The solution there was to add these lines:

```
  "github.copilot.advanced": {
    "indentationMode": {
      "python": true,
      "javascript": true,
      "javascriptreact": true,
      "jsx": true,
      "typescript": true,
      "typescriptreact": true,
      "go": true,
      "ruby": true,
      "*": true
    }
  }
 ```
 
 I'm going to see if I can dig into the VSCode extension and see how exactly `indentationMode` is used.

**Comment by gleitz** [comment]
I used mitmproxy to look at the request that VSCode is making to the `completions` endpoint.

The JSON body of the request that gives me multi-line suggestions (because I have the `indentationMode` override enabled) looks like:
```
{
  "prompt": "PROMPT HERE",
  "max_tokens": 500,
  "temperature": 0,
  "top_p": 1,
  "n": 1,
  "stop": [
    "\n\n\n"
  ],
  "stream": true,
  "extra": {
    "language": "typescript",
    "next_indent": 2,
    "trim_by_indentation": true,
    "prompt_tokens": 1247,
    "suffix_tokens": 35
  }
}
```

I then removed the `indentationMode` override in VSCode, which caused me to get single line completions again. This time the request body looked like this:

```
{
  "prompt": "PROMPT",
  "max_tokens": 500,
  "temperature": 0,
  "top_p": 1,
  "n": 1,
  "stop": [
    "\n"
  ],
  "stream": true,
  "extra": {
    "language": "typescript",
    "next_indent": 2,
    "trim_by_indentation": true,
    "prompt_tokens": 1247,
    "suffix_tokens": 35
  }
}
```

The only difference is that the request that gives multi-line suggestions is looking for a `stop` of three newlines (`"\n\n\n"`), and the single line suggestion is looking for a `stop` of a single newline (`"\n"`).

So, this is the mechanism that "allows" for single or multi-line suggestions, by letting the model generate code until you get one (single line) or three (multi-line) newlines in a row.

That said, I'm not sure how to force `agent.js` to send a `stop` of `"\n\n\n"`.

**Comment by ntc2** [comment]
I've been experiencing this issue, i.e. getting single line completions when I expect multiline completions. One thing I've noticed is that it seems to depend on the language: in Java and Rust I get multiline completions, but in Python and Haskell I get single line completions. Note that Java and Rust use curly braces to scope blocks, whereas Python and Haskell use indentation only.

However, I'm having the same experience in VSCode, and it seems related to trying Copilot out on empty files. Moreover, when I open a file that already has lots of code in it, I get multiline completions in Python and Haskell. **So I think this issue has nothing to do with copilot.el**, at least in my case.
