### ISSUE TITLE
copilot-completion doesn't do anything when called from inside an unclosed parens pair

### ISSUE THREAD

**Issue by notarock** [zerolfx/copilot.el#95]
There seems to be a conflict with copilot-completion when there is a pending opening/closing characters currently being typed in the line.

I am not sure how to explain this properly, so here's a gif example where I expect pressing `tab` to accept the completion at point, but instead the tab character is inserted. Once I remove the closing parens, I then press tab and copilot-completion works properly.

![copilot-demo](https://user-images.githubusercontent.com/25652765/221031161-bca3c6d3-9f03-4dc2-9688-365f1c2ec93d.gif)

The same goes for characters that get put after the cursor while typing, i.e. `"" {} [] ()`

I am using doom-emacs along with evil-mode and have installed and configured copilot.el using the configuration from the README.

**Comment by zerolfx** [comment]
This bug should be fixed in #86. Please upgrade the plugin.
