### ISSUE TITLE
(invalid-function (buf (current-buffer)))

### ISSUE THREAD

**Issue by mrfluffy-dev** [zerolfx/copilot.el#98]
Whenever I enter anything under `copilot-mode` I get the error 
`Error running timer ‘copilot--post-command-debounce’: (invalid-function (buf (current-buffer)))`
when I run `node /path/to/agent.js` I get 
```
Content-Length: 232

{"jsonrpc":"2.0","method":"LogMessage","params":{"level":0,"message":"[DEBUG] [agent] [2023-03-06T13:46:04.907Z] Agent service starting","metadataStr":"[DEBUG] [agent] [2023-03-06T13:46:04.907Z]","extra":["Agent service starting"]}}
```
# my config is 
```lisp
(use-package! copilot
  :hook (prog-mode . copilot-mode)
  :bind (("C-TAB" . 'copilot-accept-completion-by-word)
         ("C-<tab>" . 'copilot-accept-completion-by-word)
         :map company-active-map
         ("<tab>" . 'my-tab)
         ("TAB" . 'my-tab)
         :map company-mode-map
         ("<tab>" . 'my-tab)
         ("TAB" . 'my-tab)))
```

I took a look at all the solutions stated in #97 but Non of it worked setting `(setq copilot-log-max 1000) ` did nothing and changing `lexical-let` to `let` did nothing

# My system is 
OS: Arch Linux
Kernel: 6.2.2-arch1-1
Emacs V: 30.0.50
node V: 16.19.1

**Comment by zerolfx** [comment]
Please upgrade the plugin.

**Comment by mrfluffy-dev** [comment]
I feel stupid now I Installed just a bit before the update Thought I was on the latest. anyway thanks it works now sorry for the repetitive Issue. have a lovely day.
