### ISSUE TITLE
Cygwin Support

### ISSUE THREAD

**Issue by chrstfer** [zerolfx/copilot.el#99]
I just got copilot.el working (well, at least authenticating with github) on an emacs under cygwin with node.js installed under windows (cygwin has no node.js package).

Previously the process would fail before it began because node.js expects windows path forms but copilot.el was giving it linux/cygwin paths. Added a function copilot--cygwinify-dir and made a few other tweaks.

So far its mostly working, but I'd like to test it out a bit before I send a pull-request. First I need to get used to the thing in emacs, now that it's actually working. 

Thanks so much for getting this to a place where my incompetent butt was able to figure out what's wrong and fix it. These last few days between "oh wow, ive been sleep, copilot was released to the public *ages* ago" and now have been a hell of vscode and microsoft b.s.-ery and I am so happy to be back in emacs land.

**Comment by chrstfer** [comment]
In case you want to look, the biggest changes are these two:
```
;; node.js on windows cant understand cygwin paths
(defun copilot--cygwinify-path (dir &optional mixed)
  (let* ((mode-flag (if mixed
			"-m"
		      "-w"))	 
	 (retstr (shell-command-to-string (format "cygpath %s %s" mode-flag dir)))
	 (retlen (length retstr))
	 (ret    (cond
		  ((and (> retlen 0) (eql (aref retstr (- retlen 1)) ?\n))
		   (substring retstr 0 (- retlen 1)))
		  (t retstr))))
    ret))
```
and
```
;;; inside copilot--start-agent
                                  :process (make-process :name "copilot agent"
                                                         :command (list copilot-node-executable
									(copilot--cygwinify-path (concat copilot--base-dir "/dist/agent.js")))
                                                         :coding 'utf-8-emacs-unix
                                                         :connection-type 'pipe
                                                         :stderr (get-buffer-create "*copilot stderr*")
                                                         :noquery t)))
```

Was just about to push (i know i said I'd wait a bit, but i also wrote that hours ago and didnt submit until a few minutes ago), but I don't have my github setup to do so on this machine. Tomorrow it will have to be.

Thanks again!

**Comment by zerolfx** [comment]
Could you explain it by giving an example? What does the input/output of `copilot--cygwinify-path` look like?

**Comment by chrstfer** [comment]
It converts paths between linux pathspec strings and windows "pathspec" strings. So, replaces ^/ with C:\\ and all intermediate /'s with \\. The other direction isn't important because there's no linux-only node trying to run on some anti-cygwin abomination, at least not that i know of (and I think I might actively hinder such a project if it did exist..... lol jk)

When calling node via `(list copilot-node-executable (concat copilot--base-dir "/dist/agent.js"))` on cygwin, the node executable comes out to be just "node" and the path comes out in unix style. Node.js doesnt like either of those on windows, so the server dies before it's born (cant find agent.js) and then the create-agent function errors out. 

The error message was always the same as the error from issue #81, though obviously for completely different reasons.

**Comment by zerolfx** [comment]
The current version works on Windows, and having slashes in the path (even on Windows) is the default behavior of Emacs.
So I just wonder, is it necessary to convert slashes to backslashes?
Is it possible to make Cygwin happy only by configuring `copilot--base-dir` and `copilot-node-executable`?
